name: Integration tests
# Run on any push or PR to 'main', and once a day.
on:
  push:
    branches:
      - main
  # TODO(pmansour): re-enable this after the relevant issue is resolved.
  # https://github.com/pmansour/minimeet/issues/5
  # schedule:
  #   - cron: '30 11 * * *'
jobs:
  run-e2e-test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Prepare test credentials
        shell: bash
        env:
          GOOGLE_USERNAME: ${{ secrets.GOOGLE_USERNAME }}
          GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
        run: |
          printf '{
            "username": "%s",
            "password": "%s"
          }' "$GOOGLE_USERNAME" "$GOOGLE_PASSWORD" > test/test-creds.json
      - run: npm ci
      - name: Install xvfb
        run: sudo apt install xvfb --yes --quiet
      - run: xvfb-run npm test
